services:
  backend:
    build: #./Backend/odc
      context: https://github.com/ShineLine-data/lineBackend.git
      dockerfile: ./odc/Dockerfile2
    container_name: backend_app2
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: #./Frontend
      context: https://github.com/ShineLine-data/lineFrontend.git
      dockerfile: Dockerfile
    container_name: frontend_app2
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: odc
      POSTGRES_PASSWORD: odc123
      POSTGRES_DB: odcdb
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build: #./Backend/odc
      context: https://github.com/ShineLine-data/lineBackend.git
      # test another way
      # context: https://github.com/ShineLine-data/lineBackend.git#main/odc #this doesn't work
      dockerfile: odc/Dockerfile2
      
    command: python manage.py migrate
    depends_on:
      - db
      - backend

volumes:
  postgres_data:



